/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  access_token: string | null;
  expires_at: Int8 | null;
  id: Generated<string>;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: string;
}

export interface Destination {
  id: Generated<string>;
  image_url: string;
  name: string;
  type: string;
}

export interface Session {
  expires: Timestamp;
  id: Generated<string>;
  sessionToken: string;
  userId: string;
}

export interface Trip {
  created_at: Generated<Timestamp | null>;
  end_date: Timestamp;
  id: Generated<string>;
  name: string;
  owner_id: string;
  selected_destination_id: string | null;
  start_date: Timestamp;
  status: Generated<string | null>;
}

export interface TripAccess {
  trip_id: string;
  user_id: string;
}

export interface TripDestination {
  destination_id: string;
  trip_id: string;
}

export interface TripVotes {
  destination_id: string;
  trip_id: string;
  user_id: string;
}

export interface User {
  email: string;
  emailVerified: Timestamp | null;
  id: Generated<string>;
  image: string | null;
  name: string | null;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  Account: Account;
  destination: Destination;
  Session: Session;
  trip: Trip;
  trip_access: TripAccess;
  trip_destination: TripDestination;
  trip_votes: TripVotes;
  User: User;
  VerificationToken: VerificationToken;
}
